Api 2338 font 404 fix
department-of-veterans-affairs/vets-saml-proxy pull request #150
Opened 2020-09-25 21:37 UTC by bdgrider

[font_404_change_summary.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5285478/font_404_change_summary.docx)

Updated static assets with latest versions from formation (fonts, img, css). Made it so that only one route serves statics assets. Fixed all font 404's and removed temporary patch code from previous font 404.

2020-09-26 19:16 UTC, beaugrantham-va commented
I'm still seeing a few 404s on the error page.

```
saml-proxy_1  | {
saml-proxy_1  |   "remote-address": "::ffff:172.18.0.1",
saml-proxy_1  |   "time": "2020-09-26T19:14:46.355Z",
saml-proxy_1  |   "method": "GET",
saml-proxy_1  |   "url": "/samlproxy/webfonts/fa-solid-900.woff",
saml-proxy_1  |   "status-code": "404",
saml-proxy_1  |   "content-length": "1011",
saml-proxy_1  |   "referrer": "http://localhost:7000/samlproxy/idp/core.css",
saml-proxy_1  |   "request_id": "8a4857d0-002c-11eb-82a2-2b0b10e56b49"
saml-proxy_1  | }
```

2020-09-26 19:32 UTC, beaugrantham-va commented on saml-proxy/public/formation.min.css
> +/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}article,aside,details,figcaption,figure
Is this file necessary? I don't see it actually being referenced anywhere.

2020-09-26 19:41 UTC, beaugrantham-va requested changes

2020-09-26 19:41 UTC, beaugrantham-va commented on saml-proxy/styles/core.scss
> +$formation-asset-path: "../idp";
I recommend replacing this with an absolute path (like above).

2020-09-28 17:07 UTC, crolarlibertyva commented
Local testing in my environment shows that no 404's  are occurring for fonts.

2020-09-28 19:13 UTC, bdgrider commented on saml-proxy/public/formation.min.css
> +/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}article,aside,details,figcaption,figure
It was recommended in the formation install instructions. Removing it does not appear to have any effect on  the test procedures I went through, so ill go ahead and remove it.

2020-09-28 19:49 UTC, beaugrantham-va approved these changes

2020-09-30 12:07 UTC, merged