API-2399 migration to okta sdk
department-of-veterans-affairs/vets-saml-proxy pull request #158
Opened 2020-10-12 22:13 UTC by crolarlibertyva

This iteration uses the memory store cache with the same expiration as the node-cache with axios previously.

2020-10-13 14:10 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> -const URI = require("urijs");
I think this can be removed from package.json if it's the only use.

2020-10-13 14:12 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +    cacheStore: new MemoryStore({
Are there docs or something that say _what_ requests are cached?

2020-10-13 14:14 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_sec
This new config needs to be added to `cli.js`.

2020-10-13 14:15 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +    cacheStore: new MemoryStore({
Info I consulted was in here:
https://github.com/okta/okta-sdk-nodejs#custom-middleware

2020-10-13 14:15 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> -const URI = require("urijs");
Roger that.

2020-10-13 14:17 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +    ? config.cache_expiration_sec
These units don't match up

2020-10-13 14:28 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getAuthorizationServerInfo = async (
Can this just use `getAuthorizationServer(authServerId)`?

https://developer.okta.com/okta-sdk-nodejs/jsdocs/GeneratedApiClient.html#getAuthorizationServer__anchor

2020-10-13 14:31 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getClaims = async (authorizationServerId, oktaClient) => {
Where is this used?

2020-10-13 14:33 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getAuthorizationServerInfo = async (
Yes, will adjust.

2020-10-13 14:35 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getClaims = async (authorizationServerId, oktaClient) => {
It's not currently used yet, but it was there prior to this ticket.

2020-10-13 14:39 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> +  await oktaClient.http
Can this just use `revokeGrantsForUserAndClient(userId, clientId)`?

https://developer.okta.com/okta-sdk-nodejs/jsdocs/GeneratedApiClient.html#revokeGrantsForUserAndClient__anchor

2020-10-13 14:49 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +    ? config.cache_expiration_sec
The nodecache setting was in seconds so I I chose I picked that unit for our configuration and convert to milliseconds from that. Prefer to keep the memstore setting in milliseconds?

2020-10-13 14:55 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +    ? config.cache_expiration_sec
But there is no conversion... you're passing a value of _seconds_ into something that expects _milliseconds_.

2020-10-13 15:02 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getClaims = async (authorizationServerId, oktaClient) => {
> but it was there prior to this ticket

Was it called something else? Or in another file? I'm not seeing anything similar on the master branch.

If it's not used, let's remove it.

2020-10-13 15:26 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> +const getClaims = async (authorizationServerId, oktaClient) => {
Roger that. I'll double check with @lukemarkwordtlibertyits  too.

2020-10-13 15:32 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +    ? config.cache_expiration_sec
Got it.

2020-10-13 17:08 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> -const uriTemplates = require("uri-templates");
This dependency can go now too.

2020-10-13 17:12 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +  const keyLimit = config.cache_key_limit ? config.cache_key_limit : 100000;
I think these defaults (10k, 3600) should be unnecessary now here since they are defined in `cli.js`.

2020-10-13 17:24 UTC, beaugrantham-va commented
Merge master into this branch to pick up the fix for CodeBuild.

2020-10-13 21:09 UTC, lukemarkwordtlibertyits commented on oauth-proxy/apiClients/oktaApiClient.js
> -const axios = require("axios");
This module is very clean now. I like it!

2020-10-13 21:18 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/revokeUserGrantHandler.js
> -const getUserIds = async (config, email) => {
Glad to see a helper method go. Will make the file more readable.

2020-10-13 22:49 UTC, lukemarkwordtlibertyits requested changes

2020-10-13 22:49 UTC, lukemarkwordtlibertyits commented on oauth-proxy/apiClients/oktaApiClient.js
> +  return await oktaClient.revokeGrantsForUserAndClient(userId, clientId);
This method did not pass work when I ran my regression tests.

see [here](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5374570/API2399_Test__RegressionTests.docx)

2020-10-14 20:22 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> -const uriTemplates = require("uri-templates");
oktaApiClients.js is gone.

2020-10-14 20:23 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> -const axios = require("axios");
It's really clean now that is no longer there.

2020-10-14 20:24 UTC, crolarlibertyva commented on oauth-proxy/apiClients/oktaApiClient.js
> +  return await oktaClient.revokeGrantsForUserAndClient(userId, clientId);
@lukemarkwordtlibertyits  It's working in may setup with the curl command. Maybe the latest updates fixed your run.

2020-10-14 21:20 UTC, beaugrantham-va commented on oauth-proxy/apiClients/oktaApiClient.js
> -const uriTemplates = require("uri-templates");
But the dependency still lives on.

2020-10-15 13:26 UTC, beaugrantham-va requested changes
- [ ] Remove uri-templates dependency
- [ ] Pull in master to fix CodeBuild

2020-10-16 16:52 UTC, beaugrantham-va requested changes

2020-10-16 16:52 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
We lost the conversion of seconds to ms somewhere.

2020-10-16 16:52 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
Also I'm a bit confused by the docs (https://developer.okta.com/okta-sdk-nodejs/jsdocs/#toc39__anchor).

This property (`expirationPoll`) doesn't appear to represent cache TTL. It's the value of time that the lib proactively evicts expired entries. I can't seem to find the actual cache TTL anywhere.

So at a minimum, these property names (`expirationPoll` and `cache_expiration_seconds` are mismatched).

2020-10-16 16:52 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +      .getAuthorizationServer(authorizationServerId)
I'm getting a 500 error when I provide an `aud` as part of the authorization request.

2020-10-16 16:52 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/revokeUserGrantHandler.js
> +    .revokeGrantsForUserAndClient(userId, clientId)
I'm getting a 500 error when I attempt to delete grants.

```
curl -X DELETE \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d ' {
 "client_id": "...",
 "email": "va.api.user+idme.101@gmail.com"
}' "http://localhost:7100/oauth2/grants" 
```

2020-10-16 17:01 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +      .getAuthorizationServer(authorizationServerId)
Never-mind on this one I guess... I can't reproduce it again.

2020-10-16 17:29 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
I'll get the conversion back. not sure how that got lost.

2020-10-16 17:52 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
Gonna put this back in draft. This is not behaving correctly, on basic auth now.

2020-10-16 19:25 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/revokeUserGrantHandler.js
> +    .revokeGrantsForUserAndClient(userId, clientId)
Mine is this.
`Revoke at http://localhost:7100/oauth2/veteran-verification-apis/v1
email equals va.api.user%2Bidme.003@gmail.com
*   Trying ::1:7100...
* TCP_NODELAY set
* Connected to localhost (::1) port 7100 (#0)
> DELETE /oauth2/veteran-verification-apis/v1/grants HTTP/1.1
> Host: localhost:7100
> User-Agent: curl/7.68.0
> Accept: */*
> Content-type: application/x-www-form-urlencoded
> Content-Length: 1128
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/json; charset=utf-8
< Content-Length: 148
< ETag: W/"94-/NtojEVoTY91UEIWu2Gs7ve5D8U"
< Date: Fri, 16 Oct 2020 19:23:50 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
{"email":"va.api.user+idme.003@gmail.com","responses":[{"status":204,"userId":"00u2jpw2kx2ONsmva2p7","message":"Okta grants successfully revoked"}]}`

2020-10-16 19:29 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
- Auth is fine. I had a false alarm due to a firefox update I had on my system and ff needed to be restarted. 
- Back to ready-for-review status.
- Conversion is back. It got dropped when I moved out the memstore creation outside the okta client creation.

2020-10-16 19:49 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
> Also I'm a bit confused by the docs (https://developer.okta.com/okta-sdk-nodejs/jsdocs/#toc39__anchor).
> 
> This property (`expirationPoll`) doesn't appear to represent cache TTL. It's the value of time that the lib proactively evicts expired entries. I can't seem to find the actual cache TTL anywhere.
> 
> So at a minimum, these property names (`expirationPoll` and `cache_expiration_seconds` are mismatched).

This is in the readme for the project at https://github.com/okta/okta-sdk-nodejs#storage
`By default, expired keys are only removed on attempted retrieval. If a key is never retrieved, it will remain in the cache, which may grow until it hits maximum size.

To prevent this behavior, and instead remove expired values from memory proactively, set a value for expirationPoll and the MemoryStore will periodically scan the entire store in memory to remove expired keys.`

2020-10-16 20:00 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +  const expirationPoll = config.cache_expiration_seconds;
Yes, this is the description I am confused with.

It describes when expired keys are removed. It does not describe when a key is deemed expired.

2020-10-19 13:06 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/revokeUserGrantHandler.js
> +    .revokeGrantsForUserAndClient(userId, clientId)
Resolved with https://github.com/department-of-veterans-affairs/vets-saml-proxy/pull/158/commits/c5f46fd5a5ab44cb39718dc8f0ed525010211f6b

2020-10-19 13:16 UTC, beaugrantham-va approved these changes

2020-10-19 16:21 UTC, lukemarkwordtlibertyits commented
Looks Good!
[API2399_Test__RegressionTests-V2.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5403291/API2399_Test__RegressionTests-V2.docx)

2020-10-19 16:21 UTC, lukemarkwordtlibertyits approved these changes

2020-10-19 16:42 UTC, merged