API-2249 committing changes to parse saml handler. Still need to test…
department-of-veterans-affairs/vets-saml-proxy pull request #159
Opened 2020-10-13 18:39 UTC by bdgrider

Logged and threw error message for the case of when someone is trying to authenticate without a relay state.

2020-10-13 21:32 UTC, beaugrantham-va requested changes
I'm not sure this is actually working.

I can visit /samlproxy/idp/saml/sso and don't get an error, even though the logs clearly show that relay state / body is undefined.

```
saml-proxy_1  | {
saml-proxy_1  |   "service": "saml-proxy",
saml-proxy_1  |   "request_id": "e92df540-0d9a-11eb-8be2-7935f568e531",
saml-proxy_1  |   "time": "2020-10-13T21:27:35.317Z",
saml-proxy_1  |   "step": "from Okta",
saml-proxy_1  |   "session": "ee8742f2-35bb-4c26-9046-2f2a53f5f9e5",
saml-proxy_1  |   "level": "info",     
saml-proxy_1  |   "message": "Relay state from Okta - body: undefined query: undefined"
saml-proxy_1  | }                                                                                                          
saml-proxy_1  | {
saml-proxy_1  |   "service": "saml-proxy",
saml-proxy_1  |   "request_id": "e92df540-0d9a-11eb-8be2-7935f568e531",
saml-proxy_1  |   "action": "parseSamlRequest",      
saml-proxy_1  |   "result": "success",
saml-proxy_1  |   "session": "ee8742f2-35bb-4c26-9046-2f2a53f5f9e5",
saml-proxy_1  |   "level": "info",     
saml-proxy_1  |   "message": "User arrived from Okta. Rendering IDP login template.",
saml-proxy_1  |   "time": "2020-10-13T21:27:35.329Z"                                                                       
saml-proxy_1  | }
saml-proxy_1  | {
saml-proxy_1  |   "remote-address": "::ffff:172.20.0.1",
saml-proxy_1  |   "time": "2020-10-13T21:27:35.334Z",
saml-proxy_1  |   "method": "GET",
saml-proxy_1  |   "url": "/samlproxy/idp/saml/sso",                                                                        
saml-proxy_1  |   "status-code": "200",
saml-proxy_1  |   "content-length": "7310",                                                                                
saml-proxy_1  |   "request_id": "e92df540-0d9a-11eb-8be2-7935f568e531"
saml-proxy_1  | }
```

I'd also like to see a unit test for this.

2020-10-14 21:40 UTC, lukemarkwordtlibertyits commented
This changes breaks the verify endpoint

2020-10-14 22:13 UTC, lukemarkwordtlibertyits requested changes

2020-10-14 22:13 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +        req.authnRequest.relayState == null ||
This check should go in the `samlLogin` function

2020-10-14 22:13 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +    } else {
This else statement along with the relay state check will break the `verify` endpoint.

2020-10-14 22:13 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +        req.authnRequest.relayState == null ||
right after [this](https://github.com/department-of-veterans-affairs/vets-saml-proxy/pull/159/files#diff-31b89a2353a0eafd6b5da7f00254c006264532e90dee2065bf45018dcda549deR34) statement.

2020-10-14 22:21 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +        req.authnRequest.relayState == null ||
The reason is that this method creates an authnRequest object that is used to make a saml request to our IDPs. The object is stored in session, so it is possible to hit the `idp/saml/sso` endpoint without an authnRequest or relayState query parameter, so long as these parameters are stored in the request session.

2020-10-16 16:10 UTC, crolarlibertyva commented
Linting items need to be addressed.

2020-10-16 16:17 UTC, crolarlibertyva requested changes
Need to address lint violations.

2020-10-16 23:32 UTC, lukemarkwordtlibertyits requested changes

2020-10-16 23:32 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +    } else if (!data && !req.authnRequest) {
The parseSamlRequest is called before the samlLogin method so this check will break the /verify endpoint. There are use cases for parseSamlRequest to return null. I believe this check should be removed entirely, until we decide whether we would like to refactor this module. For now, a single check in the samlLogin method should be enough.
[API2249_Tests.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5394690/API2249_Tests.docx)

2020-10-16 23:32 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +    if (
This the empty data check in the parseSamlRequest method should be taken out this check should also include a null check on the authnRequest object.
ex. `req.authnRequest?.relayState == null`

2020-10-19 15:52 UTC, lukemarkwordtlibertyits approved these changes

2020-10-19 15:52 UTC, lukemarkwordtlibertyits commented
Looks Good!
[API2249_Tests__V2.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5403099/API2249_Tests__V2.docx)

2020-10-19 23:51 UTC, beaugrantham-va commented on saml-proxy/src/routes/handlers.js
> +      req.authnRequest?.relayState == null ||
I question whether this should be checking for `null`, or whether it should be checking for `=== undefined`.

I don't see anywhere in the code where we explicitly set this to `null`.

2020-10-20 18:00 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/handlers.js
> +      req.authnRequest?.relayState == null ||
In javascript null defines an object whereas undefined defines a type, so `null == undefined //true` but `null === undefined \\false`.
So this check should cover both nulls and undefined.

2020-10-20 18:31 UTC, beaugrantham-va approved these changes

2020-10-20 18:33 UTC, merged