Api 2418 update okta sdk
department-of-veterans-affairs/vets-saml-proxy pull request #161
Opened 2020-10-19 18:16 UTC by lukemarkwordtlibertyits

Okta SDK had outdated version of isomorphic-fetch which had an outdated node-fetch dependency with a security risk. Latest Okta SDK patch fixed this. Updated to latest.
[API2418_Tests__RegressionTests-V2.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5403899/API2418_Tests__RegressionTests-V2.docx)

2020-10-19 18:35 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/oauthHandlers.test.js
> -    getUserIdsMock.mockImplementation(() => {
There should be no userids returned for an invalid email.

2020-10-19 18:36 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/oauthHandlers.test.js
> +    expect(res.statusCode).toEqual(undefined);
I ran the master tests locally and this one was not passing.

2020-10-19 23:33 UTC, beaugrantham-va requested changes

2020-10-19 23:33 UTC, beaugrantham-va commented on oauth-proxy/tests/oauthHandlers.test.js
> +    expect(res.statusCode).toEqual(undefined);
If this is not returning a 400 then we need to fix the `revokeUSerGrantHandler` function.

This is a valid scenario where someone may try to revoke grants for a non-existent user and should get a 400 in response.

2020-10-20 16:32 UTC, crolarlibertyva requested changes

2020-10-20 16:32 UTC, crolarlibertyva commented on oauth-proxy/tests/oauthHandlers.test.js
>      expect(res.statusCode).toEqual(400);
This UT is failing for me.

2020-10-20 20:06 UTC, crolarlibertyva approved these changes
Exercised the endpoints, behaved as expected.

2020-10-21 13:07 UTC, beaugrantham-va approved these changes

2020-10-22 13:00 UTC, merged