API-3296 Removing unnecessary error logging.
department-of-veterans-affairs/vets-saml-proxy pull request #171
Opened 2020-10-30 21:18 UTC by bdgrider

2020-10-30 21:57 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
> -      this.logger.error(returnError.error_description, error);
I'll have to get a test run in to see what's gonna show in a message.

2020-10-31 00:31 UTC, beaugrantham-va requested changes

2020-10-31 00:31 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
> -      this.logger.error(returnError.error_description, error);
_Some_ amount of logging is necessary. Otherwise we will never be able to track down the cause of a problem.

2020-10-31 00:41 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
> -      this.logger.error(returnError.error_description, error);
https://github.com/axios/axios#handling-errors

2020-10-31 00:58 UTC, beaugrantham-va approved these changes

2020-11-02 13:11 UTC, crolarlibertyva reviewed
Confirmed the error message shows, but not the token.

2020-11-02 13:14 UTC, crolarlibertyva approved these changes

2020-11-02 14:00 UTC, merged