Api 3017 add document strategies to client credential flow
department-of-veterans-affairs/vets-saml-proxy pull request #175
Opened 2020-11-06 17:18 UTC by lukemarkwordtlibertyits

2020-11-06 17:46 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +class PullDocumentByLaunchStrategy {
Not sure when we would ever query by `launch`. Many tokens may be associated with the same launch.

I don't think we need to do any querying for the client credentials flow, but I don't know how that affects the design pattern we have in place that expects some sort of query.

2020-11-06 19:00 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +class PullDocumentByLaunchStrategy {
Doesnt change the pattern all to much. Will likely want to change the strategy from pullDocument to createDocument though. Changing that strategy name will make this diff log in this pr very large. I may wait to do so until this one gets merged and then do a smaller PR with just document name changes.

2020-11-10 01:41 UTC, crolarlibertyva submitted a review, later dismissed
I am still not yet sure if this isn't an issue with my configuration. But this is from a fresh start.
```
{
  "service": "oauth-proxy",
  "code": "ERR_INVALID_ARG_TYPE",
  "level": "error",
  "message": "Could not update the access token token in DynamoDBThe \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined",
  "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined\n    at prepareSecretKey (internal/crypto/keys.js:322:11)\n    at new Hmac (internal/crypto/hash.js:113:9)\n    at Object.createHmac (crypto.js:147:10)\n    at SaveDocumentLaunchStrategy.hashString [as hashingFunction] (/home/node/utils.js:77:23)\n    at SaveDocumentLaunchStrategy.saveDocumentToDynamo (/home/node/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js:13:32)\n    at TokenHandlerClient.handleToken (/home/node/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js:41:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process
/task_queues.js:97:5)\n    at async Object.tokenHandler (/home/node/oauthHandlers/tokenHandler.js:43:21)\n    at async /home/node/index.js:378:7",
  "time": "2020-11-10T01:34:18.224Z"
}
```

2020-11-10 17:09 UTC, crolarlibertyva commented
> I am still not yet sure if this isn't an issue with my configuration. But this is from a fresh start.
> 
> ```
> {
>   "service": "oauth-proxy",
>   "code": "ERR_INVALID_ARG_TYPE",
>   "level": "error",
>   "message": "Could not update the access token token in DynamoDBThe \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined",
>   "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined\n    at prepareSecretKey (internal/crypto/keys.js:322:11)\n    at new Hmac (internal/crypto/hash.js:113:9)\n    at Object.createHmac (crypto.js:147:10)\n    at SaveDocumentLaunchStrategy.hashString [as hashingFunction] (/home/node/utils.js:77:23)\n    at SaveDocumentLaunchStrategy.saveDocumentToDynamo (/home/node/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js:13:32)\n    at TokenHandlerClient.handleToken (/home/node/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js:41:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process
> /task_queues.js:97:5)\n    at async Object.tokenHandler (/home/node/oauthHandlers/tokenHandler.js:43:21)\n    at async /home/node/index.js:378:7",
>   "time": "2020-11-10T01:34:18.224Z"
> }
> ```



> I am still not yet sure if this isn't an issue with my configuration. But this is from a fresh start.
> 
> ```
> {
>   "service": "oauth-proxy",
>   "code": "ERR_INVALID_ARG_TYPE",
>   "level": "error",
>   "message": "Could not update the access token token in DynamoDBThe \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined",
>   "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"key\" argument must be of type string or an instance of Buffer, TypedArray, DataView, or KeyObject. Received undefined\n    at prepareSecretKey (internal/crypto/keys.js:322:11)\n    at new Hmac (internal/crypto/hash.js:113:9)\n    at Object.createHmac (crypto.js:147:10)\n    at SaveDocumentLaunchStrategy.hashString [as hashingFunction] (/home/node/utils.js:77:23)\n    at SaveDocumentLaunchStrategy.saveDocumentToDynamo (/home/node/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js:13:32)\n    at TokenHandlerClient.handleToken (/home/node/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js:41:47)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process
> /task_queues.js:97:5)\n    at async Object.tokenHandler (/home/node/oauthHandlers/tokenHandler.js:43:21)\n    at async /home/node/index.js:378:7",
>   "time": "2020-11-10T01:34:18.224Z"
> }
> ```
It was an issue with my config. Happy path works for me now.

2020-11-10 18:23 UTC, crolarlibertyva commented
For the client credentials route I still get the following after introspection.

`{
  "active": true,
  "scope": "launch/patient",
  "exp": 1605035817,
  "iat": 1605032217, ...
 }
 `

2020-11-11 00:29 UTC, crolarlibertyva approved these changes

2020-11-12 14:43 UTC, beaugrantham-va requested changes

2020-11-12 14:43 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +function getFromDynamoByLaunch(client, launch, TableName) {
This is never used; it should be removed.

2020-11-12 14:43 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentLaunchStrategy.js
> +          this.config.hmac_secret
This needs to be added to `cli.js`.

The two new properties also need to go into `dev-config.base.json`.

2020-11-12 14:43 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +    if (launch == null || launch === undefined || launch === "") {
Per my IDE:

```
launch == null || launch === undefined can be simplified to launch == null 
```

2020-11-12 14:43 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +class PullDocumentByLaunchStrategy {
Please create a story to track this change request.

2020-11-12 15:35 UTC, beaugrantham-va requested changes
Also need the 4 real config files updated with the new properties before this can merge.

2020-11-12 18:04 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +class PullDocumentByLaunchStrategy {
https://vajira.max.gov/browse/API-3536

2020-11-14 17:23 UTC, beaugrantham-va commented on oauth-proxy/tests/TokenHandlerTests/pullDocumentByLaunchStrategy.test.js
> +    expect(true).toBe(true);
This is not an effective unit test.

2020-11-14 17:24 UTC, beaugrantham-va commented on oauth-proxy/tests/TokenHandlerTests/saveDocumentByLaunchStrategy.test.js
> +    expect(true).toBe(true);
This is not an effective unit test.

2020-11-14 17:25 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByLaunchStrategy.js
> +    if (launch == null) {
This also needs a not-empty check otherwise an exception seems to be thrown.

2020-11-14 19:01 UTC, beaugrantham-va approved these changes

2020-11-15 21:13 UTC, dbrown-va approved these changes
Confirmed hashed token & launch stored in local dynamodb for only Client Credentials /token call.  Also confirmed empty launch is not stored.  Looks good.

I think as a follow on we will want to explore a time to live configuration.  The access token response contains a `expires_in` parameter, that I think would be a good candidate.

2020-11-17 01:06 UTC, merged