API-3309
department-of-veterans-affairs/vets-saml-proxy pull request #178
Opened 2020-11-16 14:58 UTC by bdgrider

2020-11-24 20:10 UTC, crolarlibertyva requested changes

2020-11-24 20:10 UTC, crolarlibertyva commented on saml-proxy/docker-compose.yml
> +    expose:
port mapping localhost eg
`    ports:
      - 6379:6379
`

2020-11-25 21:34 UTC, crolarlibertyva approved these changes

2020-11-30 19:15 UTC, esubocz-va commented on saml-proxy/src/routes/index.js
> +  //const cache = new RedisCache();
this comment can probably be taken out?

2020-11-30 21:27 UTC, esubocz-va approved these changes

2020-11-30 21:43 UTC, dbrown-va commented on saml-proxy/src/routes/acsHandlers.ts
> +    const sessionIndex = req?.user?.authnContext?.sessionIndex;
Out of an abundance of caution, I would lean towards adding a flag for us to be able to enable solely in dev for a couple days to ensure expected behavior prior to enabling in higher environments.

We will also need a corresponding devops PR anyway once the cache set up is in place.

2020-12-01 22:32 UTC, dbrown-va approved these changes
Confirmed locally with the `cacheEnabled` behavior both true & false.

Devops PR already merged and only enables dev & staging at this time.

2020-12-02 14:47 UTC, merged