Api 3458 hash refresh tokens
department-of-veterans-affairs/vets-saml-proxy pull request #180
Opened 2020-11-20 23:09 UTC by lukemarkwordtlibertyits

2020-11-20 23:18 UTC, beaugrantham-va requested changes

2020-11-20 23:18 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +      hashString(client_redirect, config.hmac_secret),
The redirect URI can't be hashed.

The `redirectHandler` needs this to know where to send a user after arriving from Okta.

2020-11-20 23:36 UTC, beaugrantham-va requested changes

2020-11-20 23:36 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +          hashedDocument.state,
I'm also realizing now that we can't hash state.

State is retrieved and included in token responses.

2020-11-23 21:49 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +          hashedDocument.state,
agreed

2020-11-24 19:44 UTC, dbrown-va approved these changes
Looks good and confirmed working locally.

2020-11-24 19:44 UTC, dbrown-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies/pullDocumentByCodeStrategy.js
> +    // Remove after 42 Days of PR merge (DATE - Fill out before PR).
Just these couple dates that could be added.

2020-11-27 16:33 UTC, crolarlibertyva approved these changes
All good for me.

2020-11-30 18:32 UTC, beaugrantham-va approved these changes

2020-11-30 18:56 UTC, merged