Api 3601 dynamo ttl
department-of-veterans-affairs/vets-saml-proxy pull request #181
Opened 2020-11-24 21:56 UTC by crolarlibertyva

2020-11-25 19:43 UTC, dbrown-va requested changes
We want the `exp` from the token itself, rather than the `client_assertion`, which will avoid passing the `assert_info`.

I think we can avoid modifying the client credentials strategy as well.

2020-11-30 13:46 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +    AWS.config.update(awsConfig);
Why is this same update statement run twice?

2020-11-30 13:47 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +  return dynamoDb;
How does this change affect strategies that read/write which were not updated in this PR?

2020-11-30 13:50 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +function savePayloadToDynamo(dynamoDb, payload, tableName) {
Should this function be async since it returns a promise?

2020-11-30 14:03 UTC, crolarlibertyva commented on oauth-proxy/dynamo_client.js
> +    AWS.config.update(awsConfig);
Without the 2nd update, it didn't retain the config settings on the subsequent client substantiation.

2020-11-30 14:11 UTC, crolarlibertyva commented on oauth-proxy/dynamo_client.js
> +  return dynamoDb;
This leaves the original read/writes intact, just needed to add a reference to the document client for use with the expire_on.

2020-11-30 14:15 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +  return dynamoDb;
Should new code be using `savePayloadToDynamo` and the old functions deprecated?

2020-11-30 14:20 UTC, crolarlibertyva commented on oauth-proxy/dynamo_client.js
> +  return dynamoDb;
Yes, will followup with a refactor ticket to address the comment of the module as well.

2020-11-30 19:55 UTC, beaugrantham-va approved these changes

2020-11-30 20:10 UTC, dbrown-va approved these changes

2020-11-30 20:12 UTC, dbrown-va commented
Confirmed update to use the expiration from the token (`decodedToken.exp`) itself rather the client assertion.

2020-11-30 20:14 UTC, merged