Api 3328 oauth regression script
department-of-veterans-affairs/vets-saml-proxy pull request #192
Opened 2020-12-10 01:04 UTC by lukemarkwordtlibertyits

Created e2e regression testing script for the Oauth Proxy.

## Quick Start

```
export USER_EMAIL=va.api.user+idme.001@gmail.com
export USER_PASSWORD=Password1234!
export CLIENT_ID={{ client id }}
export CLIENT_SECRET={{ client secret }}
export HOST=https://sandbox-api.va.gov/oauth2
export CC_CLIENT_ID={{ client id }}
export CC_CLIENT_SECRET={{ client secret }}
```

```
./tests/regression_tests.sh
```

[Findings__API-3228.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5669589/Findings__API-3228.docx)

2020-12-10 16:28 UTC, beaugrantham-va requested changes

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +# Simple scipt to test the Oauth Proxy.
s/scipt/script

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +#!/bin/bash
I'd like to see a quick validation up front that the required variables (`CLIENT_ID`, etc) are populated and the required third party non-GNU tools (docker, jq) are available.

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.md
> +- You must have access to VA docker hub and be signed in to pull the lighthouse-auth-utils image.
This image is now public.

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +doToken() {
There are a mix of function naming conventions in here. Likely my fault, if you used my script as a template.

I don't have a particular preference as long as they are consistent.

The program usually falls back to Google style guides as a default which recommends lower-case with underscores to separate words.

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +  echo "$1" > $expectedFile
Replace `$1` with `$expectedBody`

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +  docker pull vasdvp/lighthouse-auth-utils:latest
Probably a good idea to pull every time, regardless of the local registry. Otherwise it may be using an old release.

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
I don't understand this check... this doesn't look like a response that would be returned by the oauth-proxy.

2020-12-10 16:28 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
I don't understand this check... this doesn't look like a response that would be returned by the oauth-proxy.

2020-12-10 17:23 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
This is the proxied response from okta.

2020-12-10 17:23 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
This is the proxied response from okta.

2020-12-10 17:29 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +# Simple scipt to test the Oauth Proxy.
Still a little new to shell scripts. I do not understand this comment?

2020-12-10 18:36 UTC, beaugrantham-va commented on oauth-proxy/tests/regression_tests.sh
> +# Simple scipt to test the Oauth Proxy.
Substitute _scipt_ with _script_ (typo).

2020-12-10 19:29 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +# Simple scipt to test the Oauth Proxy.
Oh I see :/

2020-12-10 19:41 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
Added a commented out version of the assertion that should exist here. When the bug is resolved, we can add it back to the test.

2020-12-10 19:41 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/regression_tests.sh
> +expectJsonBody '{"error":"expected 200 OK, got: 401 Unauthorized"}'
Added a commented out version of the assertion that should exist here. When the bug is resolved, we can add it back to the test.

2020-12-10 20:23 UTC, crolarlibertyva commented on oauth-proxy/tests/regression_tests.md
> +export HOST=https://sandbox-api.va.gov/oauth2
Something like "BASE_OAUTH_URL" a better env name for this?

2020-12-15 14:11 UTC, beaugrantham-va commented
See #196.

2020-12-15 14:11 UTC, closed without merging