Api 3459 default category check
department-of-veterans-affairs/vets-saml-proxy pull request #202
Opened 2020-12-16 20:18 UTC by lukemarkwordtlibertyits

Preliminary PR to removing default routes. Checks for default api_category in the app config. Will use default routes if no default api_category then it will use the default routes.

[API3459-Tests.docx](https://github.com/department-of-veterans-affairs/vets-saml-proxy/files/5705316/API3459-Tests.docx)

2020-12-16 20:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/index.js
> -  router.options("/.well-known/*", corsHandler);
Does anyone know if this middleware is necessary? It is not in the broken out endpoints, but my tests are passing and I can hit the metadata endpoint.

2020-12-17 17:21 UTC, crolarlibertyva requested changes

2020-12-17 17:21 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +    0
You don't need the " > 0" for this to work.

2020-12-17 17:25 UTC, crolarlibertyva commented
Works for me. Tested with default route in place and not.

2020-12-17 18:42 UTC, crolarlibertyva approved these changes

2020-12-17 22:53 UTC, beaugrantham-va approved these changes

2020-12-17 22:54 UTC, merged