Api 4051 bad error response
department-of-veterans-affairs/vets-saml-proxy pull request #205
Opened 2020-12-18 15:03 UTC by bdgrider

2020-12-18 15:37 UTC, crolarlibertyva requested changes

2020-12-18 15:37 UTC, crolarlibertyva commented on .gitignore
> +/saml-proxy/sp-metadata.xml
I think this wasn't meant to be here.

2020-12-18 16:24 UTC, crolarlibertyva commented on .gitignore
> +/saml-proxy/sp-metadata.xml
This is fine to keep here.

2020-12-18 16:38 UTC, beaugrantham-va requested changes

2020-12-18 16:38 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
> +          .includes("expected 200 OK, got: 401 Unauthorized")
Interesting. So it's the OIDC client that returns this error. Understandable I guess.

This is the right approach (catch and rethrow an OAuth error) but I worry about using `error.error` as the value to compare here. It looks pretty free-form and subject to change (casing, punctuation, expected value(s)) at the discretion of the library owner.

It looks like value has a status code in it that might be safer.

```
{"error":"expected 200 OK, got: 401 Unauthorized","statusCode":401}
```

I recommend comparing `statusCode == 401` and then re-throwing a 401/invalid_client with a generic description (something like Client authentication failed.).

2020-12-18 16:38 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/token_tests.sh
> +expect_json_body '{"error":"invalid_client", "error_description": "Invalid value for client_id parameter."}'
This test doesn't look like it should pass. It's expecting `Invalid value for client_id parameter.` but the actual error message is `Invalid value for client_id parameter..`? Can you double check that `expect_json_body` is working correctly?

2020-12-18 16:42 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/token_tests.sh
There is a second commented token test in this file that should be enabled.

2020-12-21 20:29 UTC, beaugrantham-va requested changes

2020-12-21 20:29 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/regression_tests.sh
> +  exit 1mktemp
Revert this change.

2020-12-21 20:52 UTC, crolarlibertyva approved these changes

2020-12-22 18:50 UTC, dbrown-va approved these changes

2020-12-22 18:50 UTC, beaugrantham-va approved these changes

2020-12-22 18:51 UTC, merged