API-3494 committing initial changes.
department-of-veterans-affairs/vets-saml-proxy pull request #209
Opened 2020-12-22 22:32 UTC by bdgrider

2020-12-23 17:45 UTC, beaugrantham-va requested changes
- [x] Update title
- [ ] Add description
- [ ] Link Jira story
- [ ] Resolve conflicts

2020-12-23 18:38 UTC, beaugrantham-va requested changes

2020-12-23 18:38 UTC, beaugrantham-va commented on oauth-proxy/package-lock.json
> +<<<<<<< HEAD
This merge is incomplete.

2020-12-23 18:38 UTC, beaugrantham-va commented on oauth-proxy/tests/e2e.test.js
> +require("cls-rtracer");
This seems to be unnecessary.

2020-12-23 19:01 UTC, bdgrider commented on oauth-proxy/package-lock.json
> +<<<<<<< HEAD
Strange, I do not see this line in my dev environment and my branch says it is up to date.

2020-12-23 19:06 UTC, beaugrantham-va commented on oauth-proxy/package-lock.json
> +<<<<<<< HEAD
Strange. I pushed a clean merged copy.

2020-12-23 23:58 UTC, lukemarkwordtlibertyits requested changes

2020-12-23 23:58 UTC, lukemarkwordtlibertyits commented on oauth-proxy/logger.js
>  const { createLogger, format, transports } = require("winston");
There are two loggers that concern us, morgan and winston. Morgan logs the requests, whereas winston is the logger that logs messages such as log.inf("yada yada"). For the request_id to be useful we need to add it to both the morgan and winston loggers. This PR only adds the request_id to the morgan logger, we need to add the winston logger as well.

The `winstonMiddleware` function in the saml-proxy/src/logger.ts module will be a helpful reference.

2020-12-23 23:59 UTC, lukemarkwordtlibertyits commented on oauth-proxy/logger.js
>  const { createLogger, format, transports } = require("winston");
Current winston logs look similar to below:
```
{
	"service": "oauth-proxy",
	"error": "invalid_grant",
	"message": "Could not refresh the client session with the provided refresh token invalid_grant (The refresh token is invalid or expired.)",
	"name": "OPError",
	"error_description": "The refresh token is invalid or expired.",
	"level": "error",
	"time": "2020-12-23T23:50:54.273Z"
}
```

2020-12-30 22:58 UTC, lukemarkwordtlibertyits approved these changes
Looks good

2020-12-31 15:05 UTC, crolarlibertyva approved these changes

2021-01-04 14:31 UTC, beaugrantham-va commented
My only nitpick is the underscore being inconsistent with the other properties that all use dashes.

```
oauth-proxy_1         |   "remote-address": "::ffff:127.0.0.1",
oauth-proxy_1         |   "status-code": "200",
oauth-proxy_1         |   "content-length": "2464",
oauth-proxy_1         |   "request_id": "72403c60-4e98-11eb-8763-930cdbfbd945"
```

Given that saml-proxy has the same behavior, I'm okay with it for consistency, but did want to call it out.

2021-01-04 14:31 UTC, beaugrantham-va approved these changes

2021-01-04 15:59 UTC, merged