Updated regression tests
department-of-veterans-affairs/vets-saml-proxy pull request #212
Opened 2020-12-31 18:45 UTC by bdgrider

Updated the regression tests to revoke grants and then consent on the auth flow using changes made to the lighthouse-auth-utils bot.

2021-01-04 15:16 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/regression_tests.sh
> +"$DIR"/okta_grants_tests.sh --host="$HOST"
Is this a test or a setup for a test? If it's a test, it belongs in `# Start Tests` section.

2021-01-05 21:02 UTC, beaugrantham-va requested changes
This branch has conflicts

2021-01-05 22:53 UTC, bdgrider commented on oauth-proxy/tests/scripts/regression_tests.sh
> +"$DIR"/okta_grants_tests.sh --host="$HOST"
I believe this needs to come before the other tests and the assign_code function in order to trigger the okta consenting pages. I moved the # Start Tests section comment above the okta_grants_tests.sh to make it clear this is the first test.

2021-01-06 14:07 UTC, beaugrantham-va approved these changes

2021-01-06 14:07 UTC, merged