API 4280 Verify redirect uri is present earlier.
department-of-veterans-affairs/vets-saml-proxy pull request #216
Opened 2021-01-15 20:39 UTC by bdgrider

Added a simple check for redirect uri with an oauth2 compliant error message at the beginning of /authorization middleware function.

2021-01-19 18:38 UTC, lukemarkwordtlibertyits requested changes

2021-01-19 18:38 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  if (client_redirect === "") {
This will not catch undefined redirect_uris. ex: `curl -s \
  -w "%{http_code}" \
  -o "$curl_body" \
  "$HOST/authorization?client_id=$CLIENT_ID&scope=$SCOPE&response_type=code&aud=default" `

2021-01-20 15:37 UTC, beaugrantham-va submitted a review, later dismissed

2021-01-20 15:37 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  loginBegin.inc();
Move this back up to the top.

It's an important metric to capture the count of _all_ login attempts, regardless of why they may not complete.

2021-01-20 17:55 UTC, dbrown-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
>      await checkParameters(state, aud, issuer, logger, oktaClient);
We are doing a number of other client supplied parameter checks here.

Moving the `client_redirect` check could be worth while.  That would also address the `loginBegin.inc()` point Beau mentions above.

2021-01-20 22:57 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  if (client_redirect === undefined || client_redirect === "") {
A truthy check may be better for this statement

```
if(!client_redirect)
```

2021-01-21 15:23 UTC, dbrown-va approved these changes

2021-01-21 17:46 UTC, lukemarkwordtlibertyits approved these changes
looks good

2021-01-21 17:55 UTC, crolarlibertyva approved these changes

2021-01-21 18:31 UTC, merged