Api 3423 refactor token handler tests
department-of-veterans-affairs/vets-saml-proxy pull request #217
Opened 2021-01-15 22:04 UTC by lukemarkwordtlibertyits

Created this story after Token handler was broken into a strategy pattern. Thought is would be better to not test injected dependencies for this module.
## AC
All AC met (to an extent)
- [] A separate test module should be created for each TokenHandler module, client or strategy.
- [] All injected dependencies should be 
- [] 100% (wow!) code coverage for the TokenHandler Pattern.
    - Didn't quite think this one through. Line and statement coverage is at %100 percent for all modules. Case coverage is mostly at %100 but a few modules are in the 90s. 
- [] All reused test logic should be broken into a utility module.

## Concerns

I really had my OOP hat on when I created this story. I am starting to think that while unit testing each module instead of higher up modules (with non mocked dependencies) will lead to higher code coverage, simpler tests (for the most part) and more corner case testing, it may also lead to some false positives, or silent failure of the code base. There is also the issue of refactorability. [Here](https://medium.com/javascript-scene/mocking-is-a-code-smell-944a70c90a6a) is the blog post that made me think of this. 

Before this PR unit testing strategies was a bit hit or miss. Now it is completely consistent. The integration tests, will also mitigate some of the risk of too much mocking. I'm not saying we shouldn't refactor these tests, but I am open to a discussion and a rework of this PR if necessary. Let me know your thoughts.

## Coverage Before Changes

tokenHandler.js                                                               |     100 |      100 |     100 |     100 |                                                           
  tokenResponse.js                                                              |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses                          |   96.05 |    91.89 |     100 |   96.05 |                                                           
  tokenHandlerClient.js                                                         |   90.32 |    84.21 |     100 |   90.32 | 48-49,79                                                  
  tokenHandlerClientBuilder.js                                                  |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies |   94.12 |       50 |     100 |   94.12 |                                                           
  getPatientInfoFromLaunchStrategy.js                                           |     100 |      100 |     100 |     100 |                                                           
  getPatientInfoFromValidateEndpointStrategy.js                                 |   92.86 |       50 |     100 |   92.86 | 18                                                        
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/pullDocumentStrategies   |     100 |      100 |     100 |     100 |                                                           
  pullDocumentByAccessTokenStrategy.js                                          |     100 |      100 |     100 |     100 |                                                           
  pullDocumentByCodeStrategy.js                                                 |     100 |      100 |     100 |     100 |                                                           
  pullDocumentByLaunchStrategy.js                                               |     100 |      100 |     100 |     100 |                                                           
  pullDocumentByRefreshTokenStrategy.js                                         |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies   |     100 |    83.33 |     100 |     100 |                                                           
  saveDocumentLaunchStrategy.js                                                 |     100 |      100 |     100 |     100 |                                                           
  saveDocumentStateStrategy.js                                                  |     100 |       75 |     100 |     100 | 13                                                        
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies          |   92.59 |    72.73 |     100 |   92.59 |                                                           
  authorizationCodeStrategy.js                                                  |     100 |      100 |     100 |     100 |                                                           
  clientCredentialsStrategy.js                                                  |   86.67 |       70 |     100 |   86.67 | 30-34,48,69                                               
  refreshTokenStrategy.js                                                       |   94.59 |       75 |     100 |   94.59 | 42,59                                                     
  unsupportedGrantStrategy.js                                                   |     100 |      100 |     100 |     100 |     

## Coverage After Changes

tokenHandler.js                                                               |     100 |      100 |     100 |     100 |                                                           
  tokenResponse.js                                                              |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses                          |     100 |     97.3 |     100 |     100 |                                                           
  tokenHandlerClient.js                                                         |     100 |    94.74 |     100 |     100 | 63                                                        
  tokenHandlerClientBuilder.js                                                  |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/documentStrategies       |     100 |      100 |     100 |     100 |                                                           
  getDocumentByAccessTokenStrategy.js                                           |     100 |      100 |     100 |     100 |                                                           
  getDocumentByCodeStrategy.js                                                  |     100 |      100 |     100 |     100 |                                                           
  getDocumentByLaunchStrategy.js                                                |     100 |      100 |     100 |     100 |                                                           
  getDocumentByRefreshTokenStrategy.js                                          |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies |     100 |      100 |     100 |     100 |                                                           
  getPatientInfoFromLaunchStrategy.js                                           |     100 |      100 |     100 |     100 |                                                           
  getPatientInfoFromValidateEndpointStrategy.js                                 |     100 |      100 |     100 |     100 |                                                           
 oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies   |     100 |      100 |     100 |     100 |                                                           
  saveDocumentLaunchStrategy.js                                                 |     100 |      100 |     100 |     100 |                             [...]

2021-01-18 18:09 UTC, bdgrider requested changes
Checked branch, all unit and regression tests are passing.

2021-01-20 14:57 UTC, crolarlibertyva requested changes

2021-01-20 14:57 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/clientCredentialsStrategy.js
> +      if (error.response != undefined && error.response.status == 400) {
I would switch to using something like `if (!error && error.response.status == 400)` to foolproof against a future change that would have `error.response ==- null` or `error.response === false`.

2021-01-20 14:57 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/clientCredentialsStrategy.js
> +      } else if (error.response != undefined && error.response.status == 401) {
Same pattern as above.

2021-01-20 15:45 UTC, bdgrider approved these changes
Reviewed changes, verified all unit and regression tests are passing.

2021-01-20 17:50 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/clientCredentialsStrategy.js
> +      if (error.response != undefined && error.response.status == 400) {
IDE recommends the following change.

> Comparison error.response != undefined may cause unexpected type coercion 
> Comparison error.response.status == 400 may cause unexpected type coercion

`error.response !== undefined && error.response.status === 400`

2021-01-20 17:51 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/clientCredentialsStrategy.js
> +      } else if (error.response != undefined && error.response.status == 401) {
IDE recommends the following change.

> Comparison error.response != undefined may cause unexpected type coercion 
> Comparison error.response.status == 401 may cause unexpected type coercion

`error.response !== undefined && error.response.status === 401`

2021-01-20 18:18 UTC, beaugrantham-va requested changes

2021-01-20 18:18 UTC, beaugrantham-va commented on oauth-proxy/tests/TokenHandlerTests/getDocumentByAccessTokenStrategy.test.js
> +  it("Dynamo Error", async () => {
This test name should be more descriptive (it's testing a specific error scenario where it's looking up an access_token that does not exist).

2021-01-20 18:18 UTC, beaugrantham-va commented on oauth-proxy/tests/TokenHandlerTests/getDocumentByLaunchStrategy.test.js
> +        launch: undefined,
I think this should be a separate test. The previous scenario `body: {}` is valid and should still be covered.

2021-01-20 18:18 UTC, beaugrantham-va commented on oauth-proxy/tests/TokenHandlerTests/authorizationCodeStrategy.test.js
> +const userCollection = new Collection("", "", new ModelFactory(User));
IDE reports the following warning for the first param here.

> Argument type string is not assignable to parameter type ApiClient

2021-01-20 21:04 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/clientCredentialsStrategy.js
> +      if (error.response != undefined && error.response.status == 400) {
Check for a "truthy" value is the desired result

2021-01-21 12:55 UTC, crolarlibertyva approved these changes

2021-01-21 21:58 UTC, dbrown-va approved these changes
Confirmed changes implemented from Beau's earlier review.

2021-01-22 18:32 UTC, merged