Updating error message to include client_credentials.
department-of-veterans-affairs/vets-saml-proxy pull request #218
Opened 2021-01-18 22:29 UTC by bdgrider

2021-01-19 18:13 UTC, lukemarkwordtlibertyits requested changes
This is functional and is more descriptive than the last error. I am not sure it meets the following criteria `consider rewording to better handle a request with a missing grant_type`. I would recommend either refactoring to check for missing grant types. At the very least adding that the grant type may be missing in the error_description.

2021-01-20 15:21 UTC, beaugrantham-va requested changes

2021-01-20 15:21 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/unsupportedGrantStrategy.js
> +        "Only authorization_code, refresh_token, and client_credential grant types are supported",
https://tools.ietf.org/html/rfc6749#section-4.4.2 - `client_credentials`

2021-01-20 15:21 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClientBuilder.js
> +        error: "empty_grant_type",
`empty_grant_type` is not a valid error. I think this falls under `invalid_request`.

- [ ] Update error

2021-01-20 15:21 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClientBuilder.js
> +          "A grant type is required. Supported grant types are authorization, refresh_token, and client_credential.",
https://tools.ietf.org/html/rfc6749#section-4.4.2 - `client_credentials`

https://tools.ietf.org/html/rfc6749#section-4.1.3 - `authorization_code` (thanks for updating the other one)

2021-01-20 15:25 UTC, beaugrantham-va commented
Please add a unit test and integration test for missing grant type (if not already covered).

- [ ] Unit test for missing grant_type
- [ ] Integration test for missing grant_type

2021-01-21 01:26 UTC, dbrown-va approved these changes

2021-01-21 16:52 UTC, beaugrantham-va requested changes

2021-01-21 16:52 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenStrategies/unsupportedGrantStrategy.js
> -      error: "unsupported_grant_type",
`unsupported_grant_type` was correct here.

- [ ] Change this back

2021-01-21 17:48 UTC, lukemarkwordtlibertyits requested changes

2021-01-21 17:48 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClientBuilder.js
> +    if (req.body.grant_type === undefined || req.body.grant_type === "") {
grant_type could also be null. Truthy check here would cover all the bases 
```
if(!req.body.grant_type)
```

2021-01-22 15:12 UTC, crolarlibertyva approved these changes

2021-01-22 16:03 UTC, dbrown-va approved these changes

2021-01-22 17:21 UTC, merged