Api 3839 refactor dynamo client
department-of-veterans-affairs/vets-saml-proxy pull request #219
Opened 2021-01-19 18:17 UTC by crolarlibertyva

Dynamo client is now a class that only uses the document api for dynamo. Use of the client changed accordingly.

2021-01-20 15:02 UTC, beaugrantham-va requested changes
In general it's not clear to me when I would use `getPayloadFromDynamo` vs `queryFromDynamo`

2021-01-20 15:02 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +  savePayloadToDynamo(payload, tableName) {
Please add docs to all of these.

2021-01-20 17:41 UTC, lukemarkwordtlibertyits commented
Overall I do not have any suggestions to this branch. I like the refactoring. Having a DynamoClient that was dependent on a Dynamo Object was a strange pattern. I am glad this takes care of it. Also, the old DynamoClient naming conventions were obscured as we added more tables. For example, `saveToDynamo` saved to the refresh token table where as `saveToDynamoAccessToken` saved to the client credentials table. Its good that the methods are more generic now. Finally, this PR increased the overall code coverage from 84% to 87%!

2021-01-22 23:29 UTC, lukemarkwordtlibertyits commented on oauth-proxy/README.md
> +npm run-script jsdoc
should the out folder be in gitignore?

2021-01-22 23:44 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +    if (document && document.Item && document.Item.redirect_uri) {
could be 
```
if(document?.Item?.redirect_uri)
```

I guess it depends on preference

2021-01-22 23:53 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +  // Only would reach here upon an error
I'm not sure this is true. res.status will not return a function, with that being said, this next statement will have no outwards issues associated with it. You will probably see one of these errors in the logs

```
(node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'headers' of undefined
oauth-proxy_1         |     at setProxyResponse (/home/node/index.js:96:18)
oauth-proxy_1         |     at /home/node/index.js:128:9
oauth-proxy_1         |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
oauth-proxy_1         | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
oauth-proxy_1         | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2021-01-22 23:55 UTC, crolarlibertyva commented on oauth-proxy/README.md
> +npm run-script jsdoc
yes.

2021-01-22 23:56 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +    if (document && document.Item && document.Item.redirect_uri) {
I like that better.

2021-01-23 00:19 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +  // Only would reach here upon an error
Will check it out. This inadvertently fixed the 500 error that was referred to during grooming.

2021-01-23 00:34 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +    if (document && document.Item && document.Item.redirect_uri) {
Had to revert to get it to run in docker.

2021-01-23 00:35 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +  // Only would reach here upon an error
Didn't see this in logs for regression test.

2021-01-23 00:40 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +    if (document && document.Item && document.Item.redirect_uri) {
We should consider an upgraded docker base image.

2021-01-25 14:57 UTC, beaugrantham-va commented on oauth-proxy/dynamo_client.js
> +    params.UpdateExpression = params.UpdateExpression.slice(0, -1);
Should this be updated like the other to remove the arbitrary slice?

2021-01-25 15:09 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +          "Unable to look up the original redirect for the given state",
I would opt to be less verbose here (and below). Something like "Invalid state". I feel like this message exposes application detail/logic that is unnecessary to the user.

2021-01-25 23:41 UTC, lukemarkwordtlibertyits approved these changes
Overall looks good. This refactor helps clean the repository quite a bit.

2021-01-26 14:34 UTC, dbrown-va approved these changes
Confirmed running locally and the earlier changes requested have been implemented.

2021-01-26 17:23 UTC, merged