Api 4660 oauth proxy slugs
department-of-veterans-affairs/vets-saml-proxy pull request #227
Opened 2021-02-06 02:11 UTC by crolarlibertyva

- Currently rewrites idp slugs to its target id based on the configuration.
- Later can be expanded to do fuller rewrites using additional attributes for a given id.
- Retains default behavior is configuration does not contain any idps.

2021-02-07 17:32 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +        "attribute3": "potentially expandable attributes",
Let's remove the placeholder attributes until we actually define them.

2021-02-07 17:39 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +    "idps": [
This location (`config.routes.idps`) does not match the slug_helper's expected location (`config.idps`).

2021-02-07 17:40 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +    "idps": [
This needs to be added to cli.js.

2021-02-07 17:40 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +        "manage": "some_manage_endpoint"
Let's remove the placeholder attributes until we actually define them.

2021-02-07 17:44 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +        "id": "0ua720axlighthousexxxxxxx"
Let's set the real ID here (pointing to dev) as it's not sensitive.

- [ ] Use real ID.

2021-02-07 17:45 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +        "id": "0uahh383xssoixxxxxx",
Let's set the real ID here (pointing to dev) as it's not sensitive.

- [ ] Use real ID.

2021-02-07 17:46 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +        "slug": "ssoe",
We don't actually have an SSOe IDP yet, so let's remove this until it's ready.

- [ ] Remove SSOe.

2021-02-07 17:47 UTC, beaugrantham-va requested changes
Open devops (and oauth-proxy config repo) PR's to update real environment configs.

- [ ] Devops PR(s)
- [ ] oauth-proxy config repo PR(s)

2021-02-07 22:50 UTC, beaugrantham-va commented
Looks good.

Good to merge once the devops (and oauth-proxy config repo) PRs are created. This can go ahead of them but I want to make sure those aren't forgotten.

2021-02-08 13:39 UTC, crolarlibertyva commented
> Open devops (and oauth-proxy config repo) PR's to update real environment configs.
> 
>     * [ ]  Devops PR(s)
> 
>     * [ ]  oauth-proxy config repo PR(s)

https://github.com/department-of-veterans-affairs/devops/pull/8483

2021-02-09 02:30 UTC, beaugrantham-va approved these changes

2021-02-09 12:17 UTC, merged