Added manage endpoint to dev-config.base.json
department-of-veterans-affairs/vets-saml-proxy pull request #233
Opened 2021-02-11 21:02 UTC by lukemarkwordtlibertyits

Manage endpoint will be configurable.
```
{
  "api_category": "",
  "upstream_issuer": "https://issuer.com/oauth2/default",
  "manage_endpoint": "https://issuer.com/manage"
},
{
  "api_category": "",
  "upstream_issuer": "https://issuer.com/oauth2/noManage",
}
```

Expected Behavior

```bash
curl http://localhost:7100/oauth2/manage
```
returns `302`

```bash
curl http://localhost:7100/oauth2/noManage/manage
```
returns `404`

2021-02-12 15:57 UTC, crolarlibertyva approved these changes

2021-02-15 15:40 UTC, beaugrantham-va requested changes

2021-02-15 15:40 UTC, beaugrantham-va commented on oauth-proxy/dev-config.base.json
> +      {
This should be removed since this file represents a real config (minus the sensitive data). Good to see how it is tested though.

- [ ] Remove test config

2021-02-15 15:40 UTC, beaugrantham-va commented on oauth-proxy/tests/manageHandler.test.js
> +    let url = "http://fakemanage.com";
Recommend not using real third party domains. Swap this out for a reserved domain (example.com) or something related to va.gov.

- [ ] Swap domain out

2021-02-15 17:46 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +        await oauthHandlers.manageHandler(res, next, manage_endpoint)
I'm debating on whether this handler is unnecessary / too complex.

What if we just wrap `router.get(...)` with `if (manage_endpoint)`?

I don't see an advantage in a custom 404 response vs just letting the framework handle a missing route since it's not advertised.

2021-02-15 19:53 UTC, lukemarkwordtlibertyits commented on oauth-proxy/index.js
> +        await oauthHandlers.manageHandler(res, next, manage_endpoint)
Let me try this out.

2021-02-15 20:04 UTC, lukemarkwordtlibertyits commented on oauth-proxy/index.js
> +        await oauthHandlers.manageHandler(res, next, manage_endpoint)
I removed the handler. I think you are right, it was a bit too complicated.

2021-02-15 20:30 UTC, beaugrantham-va approved these changes

2021-02-15 20:54 UTC, merged