Adding the ability to configure grants consent on a per route basis.
department-of-veterans-affairs/vets-saml-proxy pull request #237
Opened 2021-02-16 22:00 UTC by bdgrider-va

2021-02-16 22:19 UTC, beaugrantham-va requested changes
- [x] Add story number to PR title
- [x] Add description to PR
- [x] Open devops PR for config changes
- [x] Open lighthouse-oauth-proxy-configs PR for config changes

2021-02-16 22:21 UTC, beaugrantham-va commented on oauth-proxy/cli.js
> +          enable_consent_endpoint: {
The old global option should be removed.

- [ ] Remove global option

2021-02-16 22:28 UTC, beaugrantham-va commented on oauth-proxy/cli.js
> +            description: "URL where developers can reset grants/consent.",
This description is not accurate (it's a boolean, not a URL).

- [ ] Update description

2021-02-16 22:36 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/revokeUserGrantHandler.js
>        errorMessage: "Revoking grants is disabled in this environment.",
This error message isn't accurate anymore... it's not just environment based, it's also authorization route based.

There was a recommendation on Luke's management_endpoint PR to change where this check is done that I think we should also apply here. Instead of passing `enable_consent_endpoint` through multiple layers, let's check it in index.js and let the framework throw a 404 if it's not enabled.

```
  if (enable_consent_endpoint) {
    router.delete(api_category + app_routes.grants, async (req, res, next) => {
      await oauthHandlers
        .revokeUserGrantHandler(okta_client, req, res, next)
        .catch(next);
    });
  }
```

This also satisfies the 404 requirement in the story.

2021-02-18 13:08 UTC, crolarlibertyva commented
Since you're in the module wondering if you can bump up some coverage for it:

- https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/09b1f7357d08a67e81967d306dfe7c2ba8da39c6/oauth-proxy/oauthHandlers/revokeUserGrantHandler.js#L24
- https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/09b1f7357d08a67e81967d306dfe7c2ba8da39c6/oauth-proxy/oauthHandlers/revokeUserGrantHandler.js#L54
- https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/09b1f7357d08a67e81967d306dfe7c2ba8da39c6/oauth-proxy/oauthHandlers/revokeUserGrantHandler.js#L74
- https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/09b1f7357d08a67e81967d306dfe7c2ba8da39c6/oauth-proxy/oauthHandlers/revokeUserGrantHandler.js#L103
- https://github.com/department-of-veterans-affairs/vets-saml-proxy/blob/09b1f7357d08a67e81967d306dfe7c2ba8da39c6/oauth-proxy/oauthHandlers/revokeUserGrantHandler.js#L144

2021-02-18 20:52 UTC, bdgrider-va commented
After some experimenting, I wasn't able to meaningfully increase the coverage either by mutating function arguments or tweaking mock objects.

2021-02-18 20:52 UTC, bdgrider-va commented
> Since you're in the module wondering if you can bump up some coverage for it:
> 


After some experimenting, I wasn't able to meaningfully increase the coverage either by mutating function arguments or tweaking mock objects.

2021-02-19 02:49 UTC, beaugrantham-va approved these changes

2021-02-19 14:35 UTC, crolarlibertyva approved these changes

2021-02-19 20:19 UTC, merged