First Commit!
department-of-veterans-affairs/vets-saml-proxy pull request #245
Opened 2021-03-03 23:09 UTC by lukemarkwordtlibertyits

2021-03-05 20:54 UTC, beaugrantham-va requested changes

2021-03-05 20:54 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +        redirect: true,
If a client is not retrievable, there is no way we can validate the redirect URI. This should be false.

2021-03-05 20:54 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +      redirect: true,
If a client is not retrievable, there is no way we can validate the redirect URI. This should be false.

2021-03-05 20:54 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  if (!validationError.valid && validationError.redirect) {
I can't think of any scenario where a redirect would be permitted if there is a problem with the client or redirect URI.

2021-03-05 20:54 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  if (!missingParameters.valid && missingParameters.redirect) {
I think any error once we validate client and redirect URI should be a redirect. I don't see any scenarios where we wouldn't (other than a 500, which gets bubbled up).

2021-03-08 15:24 UTC, crolarlibertyva approved these changes

2021-03-08 17:21 UTC, beaugrantham-va approved these changes

2021-03-08 18:03 UTC, merged