Api 5277 update oauth proxy depdencies
department-of-veterans-affairs/vets-saml-proxy pull request #246
Opened 2021-03-08 20:52 UTC by lukemarkwordtlibertyits

2021-03-08 21:53 UTC, lukemarkwordtlibertyits commented
# Local Auth Testing

## Confirm Happy Path is working.

- Make Authorization request.
- client_store = local
- client_store has redirect `localhost:8080/redirect`

### Expected results

- [ ] Redirect to authorization server 

## Confirm Client Redirect Miss is working.

- Make Authorization request.
- client_store = local
- client_store does not have redirect `localhost:8080/redirect`

expected results

- [ ] expected json
```json
{
    "error":	"invalid_client",
    "error_description": "The redirect URI specified by the application does not match any of the registered redirect URIs. Erroneous redirect URI: http://localhost:8080/redirect"
}
```

## Client miss in client_store

- Make Authorization request.
- client_store = local
- specified client not in client_store

expected results

- [ ] expected json
```json
{
    "error": "invalid_client",
    "error_description": "Invalid client for the authorization path",
}
```

## No Clients in client_store

- Make Authorization request.
- client_store = local
- force dynamo error 

expected results

- [ ] expected json
```json
{
    "error": "invalid_client",
    "error_description": "The client specified by the application is not valid."
}
```

## No Okta Redirect URI

- Make Authorization request.
- client_store = null
- redirect uri not registered with okta

expected results

- [ ] expected json
```json
{
    "error": "invalid_client",
    "error_description": "The redirect URI specified by the application does not match any of the registered redirect URIs. Erroneous redirect URI: ${client_redirect}"
}
```

## No Okta Client Id

- Make Authorization request.
- client_store = null
- client id not registered with okta

expected results

- [ ] expected json
```json
{
    "error": "invalid_client",
    "error_description": "The client specified by the application is not valid.",
}
```

2021-03-08 22:25 UTC, beaugrantham-va commented
I spot-checked a random dependency that wasn't listed in the changes or the future changes and there appears to be a newer minor version.

```
"express": "^4.16.4"
```

The latest express claims to be 4.17.1 - https://www.npmjs.com/package/express

2021-03-08 22:27 UTC, beaugrantham-va commented on oauth-proxy/package.json
> +    "eslint-plugin-jest": "^24.1.9",
Unrelated to the version change, but should this be in `devDependencies` instead of `dependencies`?

2021-03-09 14:46 UTC, crolarlibertyva submitted a review, later dismissed

2021-03-11 18:42 UTC, beaugrantham-va submitted a review, later dismissed

2021-03-11 19:34 UTC, crolarlibertyva requested changes

2021-03-11 19:34 UTC, crolarlibertyva commented on oauth-proxy/tests/scripts/token_tests.sh
> +    url="https://dev-api.va.gov/oauth2/health/system/v1"
Can we update the dev-config-base.json to go with the changes in this test?

2021-03-11 20:12 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/token_tests.sh
> +    url="https://dev-api.va.gov/oauth2/health/system/v1"
The dev-config.base.json already includes the new `/health/system` route. The old route is being retained until we fully decommission production/sandbox consumers to keep in sync.

2021-03-11 23:07 UTC, beaugrantham-va approved these changes

2021-03-12 15:13 UTC, crolarlibertyva approved these changes

2021-03-12 19:13 UTC, merged