Tests check for access-token and issuer saves
department-of-veterans-affairs/vets-saml-proxy pull request #254
Opened 2021-03-11 23:40 UTC by lukemarkwordtlibertyits

# Description

Add Access Token and ISS to OAuthRequestsV2 on Token requests.

# TODO

- [ ] Create PR to Add `oauth_access_token_index` to `OAuthRequestsV2`
    - [ ] Add `oauth_access_token_index` to `OAuthRequestsV2` in `dynamo_schema.js`
- [ ] Add logic to store access_token in the tokenHandlerClient.
- [ ] Unit Tests
- [ ] Manual Tests

# Tests

## Happy Path Okta

**Test Steps**

- Go through Oauth flow on default issuer.

**Expected Results**

```sh
aws dynamodb scan --table-name OAuthRequestsV2 --endpoint-url http://localhost:8080
```

should return following fields

- [ ] code
- [ ] internal_state
- [ ] redirect_uri
- [ ] state
- [ ] expires_on
- [ ] access_token
- [ ] iss

### Happy Path "IAM"

**Test Steps**

- Go through Oauth flow on IAM issuer.

**Expected Results**

```sh
aws dynamodb scan --table-name OAuthRequestsV2 --endpoint-url http://localhost:8080
```

should return following fields

- [ ] code
- [ ] internal_state
- [ ] redirect_uri
- [ ] state
- [ ] expires_on
- [ ] access_token
- [ ] iss

## Refresh

**Test Steps**

- Go through refresh flow on default issuer.

**Expected Results**

```sh
aws dynamodb scan --table-name OAuthRequestsV2 --endpoint-url http://localhost:8080
```

should return following fields

- [ ] code
- [ ] internal_state
- [ ] redirect_uri
- [ ] state
- [ ] expires_on
- [ ] refresh_token
- [ ] iss

2021-03-12 22:33 UTC, crolarlibertyva approved these changes

2021-03-15 14:35 UTC, beaugrantham-va requested changes

2021-03-15 14:35 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +              access_token: hashString(
This will only store access tokens when a refresh token is present.

We'll need this to work without a refresh token.

2021-03-15 16:40 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +              access_token: hashString(
I see what you are saying. Now it is necessary to check for the access_token instead of the refresh token. There is no situation where there will be an access_token with no refresh_token, but there are situations where the opposite is true. My changes will reflect this.

2021-03-15 19:56 UTC, beaugrantham-va requested changes

2021-03-15 19:56 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +            expires_on: Math.round(Date.now() / 1000) + 60 * 60 * 24 * 42,
From the story:

> For cases where there is no refresh_token, update TTL field based on expires value in token response (e.g. 1 hour).

2021-03-15 20:26 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +            expires_on: Math.round(Date.now() / 1000) + 60 * 60 * 24 * 42,
@beaugrantham-va : Should this be set to the exp if there's no refresh token?

2021-03-15 22:30 UTC, crolarlibertyva commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
>              expires_on: Math.round(Date.now() / 1000) + 60 * 60 * 24 * 42,
This should be the same as in the if condition.

2021-03-16 17:10 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +    this.issuer_client = issuer_client;
Is there benefit in passing this full object vs just the raw issuer that we need?

2021-03-16 18:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/README.md
> +docker run -d -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -sharedDb -inMemory
I always add this into the command so it may as well go into the ReadMe

2021-03-16 18:52 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
>              expires_on: Math.round(Date.now() / 1000) + 60 * 60 * 24 * 42,
Regarding Larry's previous comment about the expires_on logic should take into account a lack of a refresh token down here. I do not believe that is true.  The only way A document from OAuthRequests(V1) could make it here is if it had a refresh token and was created before the internal state logic was added.

2021-03-16 18:54 UTC, crolarlibertyva approved these changes

2021-03-17 17:38 UTC, dbrown-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
>              expires_on: Math.round(Date.now() / 1000) + 60 * 60 * 24 * 42,
Agreed, that scenario should only occur with the Refresh Token flow at this point.

2021-03-17 18:10 UTC, dbrown-va approved these changes
Changes look good.

The access token as a secondary index looks good in the local dynamo_schema.js.  Since we aren't querying on it yet, I don't think that devops support request would technically be a blocker.

2021-03-18 13:43 UTC, beaugrantham-va approved these changes

2021-03-18 16:23 UTC, merged