Grab Scopes from Token Objects instead of Access Token
department-of-veterans-affairs/vets-saml-proxy pull request #256
Opened 2021-03-12 22:49 UTC by lukemarkwordtlibertyits

- [ ] Remove reference to decoded Access token
  - tokenHandlerClient
  - saveDocumentStateStrategy
- [ ] Unit tests work
- [ ] Regression tests work

2021-03-15 14:55 UTC, beaugrantham-va requested changes

2021-03-15 14:55 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/saveDocumentStrategies/saveDocumentStateStrategy.js
> +        if (tokens.scope && tokens.scope.includes("launch")) {
`decodedToken.scp` is an array while `tokens.scope` is a string.

Using `.includes` will result in different behavior here. It needs to match `launch` exactly.

2021-03-15 14:55 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/tokenHandlerClient.js
> +      } else if (tokens.scope.includes("launch") && launch) {
`decoded.scp` is an array while `tokens.scope` is a string.

Using `.includes` will result in different behavior here. It needs to match `launch` exactly.

2021-03-15 15:52 UTC, lukemarkwordtlibertyits commented
To test Regex:

```js
let arr = "launch patient/launch".split(/(\s)/);

arr.forEach(element => console.log(element));
```

https://jsfiddle.net/vh93u851/4/

2021-03-16 16:31 UTC, beaugrantham-va commented
> To test Regex:
> 
> ```js
> let arr = "launch patient/launch".split(/(\s)/);
> 
> arr.forEach(element => console.log(element));
> ```
> 
> https://jsfiddle.net/vh93u851/4/

Using a capture group in this regular expression populates the array with unnecessary elements (size = 3).

> If separator is a regular expression with capturing parentheses, then each time separator matches, the results (including any undefined results) of the capturing parentheses are spliced into the output array.

We should drop the capture group or use a string literal (`' '`) to reduce the number of elements to search through (size = 2).

2021-03-18 13:58 UTC, beaugrantham-va approved these changes

2021-03-18 17:06 UTC, merged