API-5571 audience config
department-of-veterans-affairs/vets-saml-proxy pull request #260
Opened 2021-03-16 22:05 UTC by crolarlibertyva

- Adds the audience setting in the config for each app category

2021-03-18 14:09 UTC, beaugrantham-va requested changes
Needs corresponding devops config PR.

2021-03-18 14:16 UTC, beaugrantham-va requested changes
Linting fails.

2021-03-22 23:08 UTC, lukemarkwordtlibertyits reviewed
Looks good, my only comment is that the AuthorizationHandler grabs the Audience from the authorizationServer. This will likely cause issues with the new Issuers. It may be worth using the audience from the config in this check. Also this will be less costly!

2021-03-23 00:37 UTC, beaugrantham-va commented on oauth-proxy/cli.js
> +            description: "The audience for the app catetory.",
s/catetory/category

2021-03-23 00:49 UTC, beaugrantham-va requested changes
Can you pull the latest master?

2021-03-23 00:49 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
> -  async createPatientInfo(tokens, decoded) {
Anywhere that calls this function needs to be updated to match the new signature.

2021-03-23 00:49 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
> -  async createPatientInfo(tokens, decoded) {
A side effect of changing this signature is that you'll need to change the signature of the other classes that implement the same "interface" - getPatientInfoFromLaunchStrategy.js

2021-03-25 14:42 UTC, bdgrider-va commented on oauth-proxy/tests/TokenHandlerTests/tokenHandler.test.js
> +  (audience = "https://sandbox-api.va.gov/services/fhir"), (next = jest.fn());
I think the linter might have done this? Changing it back.

2021-03-25 14:57 UTC, beaugrantham-va requested changes
Still need to pull in the latest master

2021-03-25 14:57 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromLaunchStrategy.js
>    // eslint-disable-next-line no-unused-vars
This eslint directive can be removed now.

2021-03-25 15:03 UTC, bdgrider-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromLaunchStrategy.js
>    // eslint-disable-next-line no-unused-vars
It's still needed for the tokens parameter.

2021-03-25 15:06 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromLaunchStrategy.js
>    // eslint-disable-next-line no-unused-vars
You're totally right. My bad.

2021-03-25 21:58 UTC, lukemarkwordtlibertyits requested changes
This is kindof a tough one to spot, but I am not sure that the config audience ever gets passed through. See this log on the Authorization Handler.

![image](https://user-images.githubusercontent.com/65039481/112549058-d09ac180-8d82-11eb-912f-c441faf7cc4e.png)

If the audience was passed then there would also be an "expected" field in that message.

I think the same is true in the refresh flow.

2021-03-26 18:38 UTC, bdgrider-va commented
> This is kindof a tough one to spot, but I am not sure that the config audience ever gets passed through. See this log on the Authorization Handler.
> 
> ![image](https://user-images.githubusercontent.com/65039481/112549058-d09ac180-8d82-11eb-912f-c441faf7cc4e.png)
> 
> If the audience was passed then there would also be an "expected" field in that message.
> 
> I think the same is true in the refresh flow.

Good catch, just fixed this.

![image](https://user-images.githubusercontent.com/6391122/112678084-e66ebc00-8e40-11eb-9bcb-4c6052bc820b.png)

2021-03-30 14:18 UTC, beaugrantham-va requested changes

2021-03-30 14:18 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +const checkParameters = async (state, aud, audience, logger) => {
These param names (`aud`, `audience`) need to be more descriptive and needs `@param` documentation.

2021-03-30 14:25 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  audience,
If not, you'll need to update the jsdoc.

2021-03-30 20:48 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +    if (!(aud === audience)) {
Is there a difference between `!(aud === audience)` and `aud !== audience`? Not saying I know... genuinely curious.

2021-03-30 21:53 UTC, bdgrider-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +    if (!(aud === audience)) {
It appears that they are both "identity" comparisons, where both type and value are evaluated. So
"2"!==2 and !("2"===2) both evaluate to true

![image](https://user-images.githubusercontent.com/6391122/113061901-d0cefe80-9180-11eb-8d3b-531838f05fd1.png)

2021-03-30 23:29 UTC, bdgrider-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +  audience,
It does appear that is the case, removing the audience parameter now.

2021-03-31 22:55 UTC, lukemarkwordtlibertyits requested changes

2021-03-31 22:55 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> +    if (!(aud === audience)) {
If all things are equal than I think `!==` is preferable. To me its easier to read.

2021-03-31 22:55 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
> +    this.audience = audience;
I added a debugging line in this class to check that the audience parameter was being passed in. It is `undefined` my setup is pointing at the v1 validation endpoint so I am not sure why it is passing, still if this is a field of this class, it should be populated.

May be worth looking into whether this field is actually necessary any more?

2021-04-01 19:14 UTC, bdgrider-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/getPatientInfoStrategies/getPatientInfoFromValidateEndpointStrategy.js
> +    this.audience = audience;
Just fixed this. I had missed a second instantiation of the GetPatientInfoFromValidateEndpointStrategy class in the tokenHandlerClientBuidler.

2021-04-01 22:31 UTC, lukemarkwordtlibertyits submitted a review, later dismissed
Looks good!

2021-04-05 14:01 UTC, beaugrantham-va approved these changes

2021-04-05 14:41 UTC, merged