API-5575 - /claims service
department-of-veterans-affairs/vets-saml-proxy pull request #264
Opened 2021-03-21 23:58 UTC by beaugrantham-va

https://vajira.max.gov/browse/API-5575

Adds a service to retrieve limited claims about a token without regard to authz route. These claims would ordinarily be found in a decoded JWT. This service is primarily intended for opaque tokens without a full introspection.

Current claims returned include:
* `{ iss: "issuer" }`

2021-03-21 23:59 UTC, beaugrantham-va commented on oauth-proxy/index.js
> -  const proxyRequestToOkta = (
This method is no longer specific to a backend so it has been renamed.

2021-03-22 15:00 UTC, dbrown-va approved these changes

2021-03-22 15:46 UTC, bdgrider-va submitted a review, later dismissed
Verified linting, unit tests, and regression tests all pass.

2021-03-22 15:46 UTC, bdgrider-va commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +    expect(res.status).toHaveBeenCalledWith(400);
Should this be 401? Reading the story makes it seem like it should be.

2021-03-22 15:55 UTC, beaugrantham-va commented on .gitignore
> +/oauth-proxy/tests/scripts/setup-tests.sh
It's a local file I use to set up my environment for running the regression tests.

2021-03-22 15:57 UTC, beaugrantham-va commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +    expect(res.status).toHaveBeenCalledWith(400);
Good observation. I meant to go back and update the story and I'll do that now.

* If the request is not complete (does not contain a token) the error should reflect that - 400 bad request.
* Otherwise a 403 (refuse to authorize a valid request).

2021-03-22 16:43 UTC, lukemarkwordtlibertyits requested changes
Found one typo and left a couple comments about duplicated code.

2021-03-22 16:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/scripts/claims_tests.sh
> +  echo -e "\tFAIL - Some introspect tests did not pass."
Should be `  echo -e "\tFAIL - Some claims tests did not pass."`

2021-03-22 16:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +const config = {
There is a function called `createFakeConfig` in `testUtils.js` it sets up an object like this, with all the config values aswell. I think the value of having a complete fake config outweighs the overhead of having those extra values in there.

2021-03-22 16:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +const logger = { error: jest.fn() };
This is less important than the config comment but there is another function in the `testUtils.js` file called `buildFakeLogger` which mocks a logger that is a bit more complete.

2021-03-22 16:43 UTC, lukemarkwordtlibertyits commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +function mockDynamoClient(payload) {
In `testUtils.js` there is a function called `buildFakeDynamoClient`  which does this.

2021-03-22 17:04 UTC, lukemarkwordtlibertyits commented on oauth-proxy/index.js
> +    router.post(config.routes.app_routes.claims, async (req, res, next) => {
Why would this be a Post with the token in the body instead of a Get with the token as a Bearer?

2021-03-22 17:28 UTC, beaugrantham-va commented on oauth-proxy/index.js
> +    router.post(config.routes.app_routes.claims, async (req, res, next) => {
This should resemble /introspect as much as it can, which takes a token in the body.

If and when we add authorization the "Authorization" header will be reserved for that... be it a Bearer token or an API key.

2021-03-22 18:17 UTC, beaugrantham-va commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +const config = {
This now uses the referenced config.

2021-03-22 18:18 UTC, beaugrantham-va commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +const logger = { error: jest.fn() };
This now uses the referenced mock logger.

2021-03-22 18:18 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/claims_tests.sh
> +  echo -e "\tFAIL - Some introspect tests did not pass."
Good catch. This has been updated.

2021-03-22 18:20 UTC, beaugrantham-va commented on oauth-proxy/tests/testUtils.js
> +            authorization_endpoint: "http://example.com/authorization",
These were just updated to reference non-existent domains.

2021-03-22 18:22 UTC, beaugrantham-va commented on oauth-proxy/tests/testUtils.js
> +const mockLogger = () => {
Added function with a name to better reflect what this is (a mock implementation).

Refactoring existing tests is beyond the scope of this activity.

2021-03-22 18:23 UTC, beaugrantham-va commented on oauth-proxy/tests/testUtils.js
> +const defaultConfig = () => {
Added function with a name to better reflect what this is (a default config for testing).

Refactoring existing tests is beyond the scope of this activity.

2021-03-22 18:59 UTC, beaugrantham-va commented on oauth-proxy/tests/oauthHandlers/claimsHandler.test.js
> +function mockDynamoClient(payload) {
I've used the existing mock object where possible.

2021-03-22 19:00 UTC, beaugrantham-va commented on oauth-proxy/tests/testUtils.js
> +function mockDynamoClient(mockRecord) {
Added function with a name to better reflect what this is (a mock implementation).

Refactoring existing tests is beyond the scope of this activity.

2021-03-22 22:49 UTC, lukemarkwordtlibertyits submitted a review, later dismissed
Looks Good!

2021-03-25 20:02 UTC, bdgrider-va approved these changes
Looks good, verified all tests again.

2021-03-26 15:15 UTC, crolarlibertyva commented on oauth-proxy/tests/scripts/regression_tests.sh
> +"$DIR"/claims_tests.sh --host="$HOST"
Should we add a corresponding flag to the test for deployments that don't yet support the claims service?

2021-03-26 15:20 UTC, crolarlibertyva commented on oauth-proxy/index.js
> +    router.post(config.routes.app_routes.claims, async (req, res, next) => {
Want to include that if/when this service results in a subsequent call to introspect (upstream) the client creds will have to be passed forward to that call. But I like that fact this removes the client creds issue from the SPIKE finding.

2021-03-26 15:22 UTC, crolarlibertyva submitted a review, later dismissed

2021-03-30 17:24 UTC, beaugrantham-va commented on oauth-proxy/tests/scripts/regression_tests.sh
> +"$DIR"/claims_tests.sh --host="$HOST"
Added a flag (`--test-claims`) to optionally test the claims service.

2021-04-01 20:19 UTC, dbrown-va approved these changes
Confirmed most recent optional `--test-claims` addition.

Configurations merged to enable dev.

2021-04-01 20:21 UTC, merged

2021-04-01 20:27 UTC, bdgrider-va approved these changes
Ran linting, unit tests, and regression tests with --test-claims flag, all passed.