Updating acorn to 8.1.0.
department-of-veterans-affairs/vets-saml-proxy pull request #279
Opened 2021-04-08 18:36 UTC by bdgrider-va

2021-04-09 21:30 UTC, beaugrantham-va commented
Breaking changes for 8.0.0

> ```
> ### Breaking changes
> 
> The `ecmaVersion` option is now required. For the moment, omitting it will still work with a warning, but that will change in a future release.
> 
> Some changes to method signatures that may be used by plugins.
> ```

https://github.com/acornjs/acorn/releases/tag/8.0.0

2021-04-12 20:07 UTC, lukemarkwordtlibertyits reviewed
Does not appear to be used and all the regression and penetration testing passed. There does seem to still be references to acorn in the package.lock. Some dependencies use it as a sub-dependency. It is unclear whether these dependencies are used. For example `acorn-node` does not appear to be used. Maybe we could get rid of some of these dependencies aswell?

2021-04-12 21:20 UTC, bdgrider-va commented
> Does not appear to be used and all the regression and penetration testing passed. There does seem to still be references to acorn in the package.lock. Some dependencies use it as a sub-dependency. It is unclear whether these dependencies are used. For example `acorn-node` does not appear to be used. Maybe we could get rid of some of these dependencies aswell?

I see acorn-node as a child dependency of uswds, which we do need for styling. If this existed at the top level I would be all for removing it, but that is not the case.

2021-04-13 13:31 UTC, beaugrantham-va requested changes
Please update the PR description to reflect that the dependency was removed (not updated).

2021-04-13 21:06 UTC, lukemarkwordtlibertyits approved these changes
Looks good

2021-04-13 23:48 UTC, esubocz-va approved these changes

2021-04-14 14:36 UTC, beaugrantham-va approved these changes

2021-04-14 14:36 UTC, merged