Remove Deprecated OAuthRequestsV1  Functionality
department-of-veterans-affairs/vets-saml-proxy pull request #281
Opened 2021-04-09 19:20 UTC by lukemarkwordtlibertyits

# Description

After 42 Days of Implementing OAuthRequestsV2,  OAuthRequestsV1 can be removed.

# TODO

- [ ] Remove code from getDocumentByCodeStrategy
- [ ] Remove code from getDocumentByRefreshTokenStrategy
- [ ] Remove code from saveDocumentStateStrategy
- [ ] Remove code from redirectHandler
- [ ] Remove OAuthRequests from CLI
- [ ] Remove OAuthRequests from dev-config.json
- [ ] Remove OAuthRequests from createFakeConfig method in testUtils.js

# Tests

- [ ] Regression Tests

... What else ?

2021-04-12 19:56 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +  // REMOVE
Is this PR ready?

2021-04-13 16:26 UTC, lukemarkwordtlibertyits commented on oauth-proxy/oauthHandlers/redirectHandler.js
> +  // REMOVE
My bad

2021-04-14 13:33 UTC, beaugrantham-va requested changes

2021-04-14 13:33 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/tokenHandlerStrategyClasses/documentStrategies/getDocumentByRefreshTokenStrategy.js
> -    if (!document) {
This block of code belongs with the deferred part of the story (rejecting stateless tokens).

I think this should remain in place until we get to that second story. It allows us to have continued visibility into these tokens for a bit longer.

2021-04-14 17:50 UTC, lukemarkwordtlibertyits commented
I have confirmed that the refresh_token retrieval warning is working after adding it back in

![image](https://user-images.githubusercontent.com/65039481/114756031-8bc9d100-9d17-11eb-9481-94ea5306b4ab.png)

2021-04-16 18:21 UTC, beaugrantham-va approved these changes

2021-04-16 19:43 UTC, bdgrider-va approved these changes
Verified tests pass.

2021-04-19 19:12 UTC, beaugrantham-va commented
@lukemarkwordtlibertyits Please open a PR to remove the deprecated config from the real config files.

2021-04-19 19:13 UTC, merged