Api 6050 add dev config base json
department-of-veterans-affairs/vets-saml-proxy pull request #292
Opened 2021-04-26 18:28 UTC by lukemarkwordtlibertyits

2021-04-26 20:13 UTC, crolarlibertyva submitted a review, later dismissed

2021-04-27 13:24 UTC, beaugrantham-va requested changes
This wasn't included in the story, but please update the parent README section where it talks about dev-config.json.

https://github.com/department-of-veterans-affairs/vets-saml-proxy#running-locally

2021-04-27 15:32 UTC, beaugrantham-va commented on saml-proxy/README.md
> +A functional dev-config file can be found in the [saml-proxy-configs](https://github.com/department-of-veterans-affairs/vets-saml-proxy/pull/292) repository.
This should link to the repo, not a PR.

2021-04-27 15:34 UTC, beaugrantham-va commented on README.md
> +config file you can run `npm run-script start-dev` in order to run the proxy with your code changes. A fully function dev-config file can be found in the [saml-proxy-configs](https://github.com/depar
This should replace the paragraph below, which references a repo not used by Lighthouse anymore (vets-contrib).

2021-04-28 12:35 UTC, crolarlibertyva approved these changes

2021-04-28 12:54 UTC, beaugrantham-va approved these changes

2021-04-28 12:54 UTC, merged