update oauth proxy dev config base json
department-of-veterans-affairs/vets-saml-proxy pull request #293
Opened 2021-04-26 21:53 UTC by lukemarkwordtlibertyits

# Description

Make the oauth-proxy's dev-config.base.json more generic.

# Related PRs

https://github.com/department-of-veterans-affairs/lighthouse-oauth-proxy-configs/pull/33

2021-04-26 21:53 UTC, lukemarkwordtlibertyits commented on oauth-proxy/README.md
> +A functional dev-config.json file can be pulled from the oauth-proxy-configs repository.
Should I link the actual repository?

2021-04-27 13:25 UTC, beaugrantham-va commented on oauth-proxy/README.md
> +A functional dev-config.json file can be pulled from the oauth-proxy-configs repository.
Yes please add a link.

2021-04-27 13:39 UTC, beaugrantham-va requested changes
This wasn't included in the story, but please update the parent README section where it talks about dev-config.json.

https://github.com/department-of-veterans-affairs/vets-saml-proxy#running-locally-1

2021-04-27 15:34 UTC, beaugrantham-va commented on README.md
> +created that config you can run `npm start` to run the OAuth proxy with the code changes. A dev-config file can be found in the [oauth-proxy-configs](https://github.com/department-of-veterans-affairs
This should replace the paragraph below, which references a repo not used by Lighthouse anymore (vets-contrib).

2021-04-28 12:58 UTC, beaugrantham-va approved these changes

2021-04-28 13:03 UTC, merged