remove aud warning logging
department-of-veterans-affairs/vets-saml-proxy pull request #294
Opened 2021-04-27 17:36 UTC by esubocz-va

related story: https://vajira.max.gov/browse/API-6136

2021-04-27 17:38 UTC, beaugrantham-va requested changes

2021-04-27 17:38 UTC, beaugrantham-va commented on oauth-proxy/oauthHandlers/authorizeHandler.js
> -  if (requestAudience) {
These params should be removed from the signature, the docs, and the call since they are not being used anymore.

2021-04-27 18:57 UTC, beaugrantham-va commented
It looks like linting is not enforced with the new CodeBuild pipeline. I've opened a story to fix this - https://vajira.max.gov/browse/API-6709.

There are a couple warnings, if you could address them please.

```
/vets-saml-proxy/oauth-proxy/oauthHandlers/authorizeHandler.js
   39:29  error  'aud' is assigned a value but never used                  no-unused-vars
   59:41  error  Replace `⏎····state,⏎····logger⏎··` with `state,·logger`  prettier/prettier
  127:26  error  Replace `⏎··state,⏎··logger⏎` with `state,·logger`        prettier/prettier
```

2021-04-27 20:45 UTC, beaugrantham-va approved these changes

2021-04-28 13:35 UTC, crolarlibertyva approved these changes

2021-04-28 13:36 UTC, merged