Update saml proxy UUID
department-of-veterans-affairs/vets-saml-proxy pull request #297
Opened 2021-05-04 20:03 UTC by lukemarkwordtlibertyits

UUID dependency should be updated:

2021-05-05 13:54 UTC, esubocz-va submitted a review, later dismissed

2021-05-05 20:14 UTC, beaugrantham-va requested changes

2021-05-05 20:14 UTC, beaugrantham-va commented on saml-proxy/src/routes/index.js
> +import uuidv4 from "uuid";
I don't believe this is correct. When I expirement, `uuidv4` is undefined.

According to the [docs](https://www.npmjs.com/package/uuid), this should be `import { v4 as uuidv4 } from 'uuid';`.

2021-05-05 22:45 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/index.js
> +import uuidv4 from "uuid";
I seemed to have confused uuid with rtracer. I will correct this.

2021-05-05 23:10 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/index.js
> +import uuidv4 from "uuid";
So I found that with the incorrect import a session id will still be created but it will be a bit of a different format

**incorrect import**

![image](https://user-images.githubusercontent.com/65039481/117220506-9a5e5200-adc4-11eb-9679-825a6b729f5a.png)

**correct import**

![image](https://user-images.githubusercontent.com/65039481/117220592-c083f200-adc4-11eb-928d-cfec6fd96b0f.png)

2021-05-05 23:11 UTC, lukemarkwordtlibertyits commented on saml-proxy/src/routes/index.js
> +import uuidv4 from "uuid";
I guess the express-session defaults to underscores; whereas, uuid.v4 does dashes

2021-05-06 13:33 UTC, beaugrantham-va approved these changes

2021-05-06 14:53 UTC, merged